### ISSUE TITLE
Error 500 because of mysql_connect() in PHP 7.0.0 and higher

### ISSUE THREAD

**Issue by lepis** [oleg-goodzon/dub#1]
После настройки всех конфигов ловлю ошибку 500:

>  PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /www/htdocs/dub/www/class/class.DB.php:29\nStack trace:\n#0 /www/htdocs/dub/www/initd.php(26): DB->__construct()\n#1 /www/htdocs/dub/www/index.php(2): require_once('/www/htdocs/...')\n#2 {main}\n  thrown in /www/htdocs/dub/www/class/class.DB.php on line 29

Расширение mysql_connect выпилили из PHP 7.0.0, вместо него нужно использовать *mysqli_connect()*.

Хорошо бы в git пошарить не архив, а именно код, я бы мог предлагать пулл реквесты.

Также хотел бы помочь проекту как тестировщик :)

**Comment by lepis** [comment]
Попытался везде по коду заменить mysql_* на mysqli_*
Теперь так:

> [Mon Oct 22 12:22:13.596295 2018] [php7:warn] [pid 30648] [client 195.208.49.40:43440] PHP Warning:  mysqli_error() expects exactly 1 parameter, 0 given in /www/htdocs/dub/www/class/class.DB.php on line 35

> [Mon Oct 22 12:22:13.596430 2018] [php7:error] [pid 30648] [client 195.208.49.40:43440] PHP Fatal error:  Uncaught Exception in /www/htdocs/dub/www/class/class.DB.php:36\nStack trace:\n#0 /www/htdocs/dub/www/initd.php(26): DB->__construct()\n#1 /www/htdocs/dub/www/index.php(2): require_once('/www/htdocs/...')\n#2 {main}\n  thrown in /www/htdocs/dub/www/class/class.DB.php on line 36

**Comment by oleg-goodzon** [comment]
Попытаюсь залить не архивом а распакованный. И да, в 7м нужно чуть изменить класс DB. У меня кстати есть новая версия, которая работает именно с mysqli функциями.
